# Generated by Django 3.1.2 on 2021-04-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='state',
        ),
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='artist',
            name='hometown',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(default='none', max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(default='none', max_length=200, unique=True),
        ),
    ]
