# Generated by Django 3.1.2 on 2020-11-22 21:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lmn', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fav_artist',
            new_name='favoriteArtist',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fav_show',
            new_name='favoriteShow',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fav_venue',
            new_name='favoriteVenue',
        ),
    ]
