# Generated by Django 3.1.2 on 2020-12-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_note_notes'),
        ('lmn', '0003_merge_20201209_1414'),
        ('lmn', '0003_auto_20201206_1550'),
    ]

    operations = [
    ]
