# Generated by Django 3.1.2 on 2020-11-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_auto_20201122_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favoriteArtist',
            new_name='favorite_Artist',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='favoriteShow',
            new_name='favorite_Show',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='favoriteVenue',
            new_name='favorite_Venue',
        ),
    ]
