# Generated by Django 3.1.2 on 2021-05-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='Rate',
            field=models.CharField(choices=[('', ''), ('Terrible', 'Terrible'), ('Bad', 'Bad'), ('Not bad', 'Not bad'), ('Good', 'Good'), ('Great', 'Great')], default='0', max_length=8),
        ),
        migrations.AddField(
            model_name='note',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
