# Generated by Django 3.1.2 on 2020-12-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_note_photo'),
        ('lmn', '0004_auto_20201125_0016'),
    ]

    operations = [
    ]
