# Generated by Django 3.1.2 on 2021-05-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_auto_20210508_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='show',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lmn.show', unique=True),
        ),
    ]
