# Generated by Django 3.1.2 on 2021-05-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_auto_20210508_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Rate',
        ),
        migrations.RemoveField(
            model_name='note',
            name='photo',
        ),
    ]
