# Generated by Django 3.1.2 on 2020-11-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_auto_20201116_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(),
        ),
    ]
