# Generated by Django 3.1.2 on 2021-05-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_note_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='score',
        ),
        migrations.AddField(
            model_name='note',
            name='Rate',
            field=models.CharField(choices=[('0', ''), ('1', 'Terrible'), ('2', 'Bad'), ('3', 'Not bad'), ('4', 'Good'), ('5', 'Great')], default='0', max_length=5),
        ),
    ]
