# Generated by Django 3.1.2 on 2021-05-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20210508_2039'),
        ('lmn', '0004_auto_20210505_2004'),
    ]

    operations = [
    ]
