# Generated by Django 3.1.2 on 2020-11-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20201116_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateTimeField(),
        ),
    ]
