# Generated by Django 3.1.2 on 2021-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0006_merge_20210505_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Rate',
            field=models.CharField(choices=[('', ''), ('Terrible', 'Terrible'), ('Bad', 'Bad'), ('Not bad', 'Not bad'), ('Good', 'Good'), ('Great', 'Great')], default='0', max_length=8),
        ),
    ]
