# Generated by Django 3.1.2 on 2021-05-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0006_merge_20210509_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='show',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lmn.show'),
        ),
    ]
