# Generated by Django 3.1.2 on 2021-04-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0009_rename_userprofile_profile'),
        ('lmn', '0007_auto_20210421_0204'),
    ]

    operations = [
    ]
