# Generated by Django 3.2 on 2021-04-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0009_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, to='lmn.Badge'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shows_seen',
            field=models.ManyToManyField(blank=True, null=True, to='lmn.Show'),
        ),
    ]
