# Generated by Django 3.2 on 2021-04-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0010_auto_20210428_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, to='lmn.Badge'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shows_seen',
            field=models.ManyToManyField(blank=True, to='lmn.Show'),
        ),
    ]
