# Generated by Django 3.1.7 on 2021-05-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0011_auto_20210428_1726'),
        ('lmn', '0010_merge_20210428_1449'),
    ]

    operations = [
    ]
