# Generated by Django 3.1.7 on 2021-05-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0012_merge_20210502_0408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('show_date', 'artist', 'venue')},
        ),
    ]
