# Generated by Django 3.1.7 on 2021-05-06 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0014_auto_20210505_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showrating',
            name='rating_out_of_five',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
