# Generated by Django 3.1.7 on 2021-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0015_auto_20210506_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='number_notes',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
