# Generated by Django 3.1.7 on 2021-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0016_badge_number_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='number_notes',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
